---
title: "SAT and Teacher Salaries "
output: html_document
---


```{r}
satDF = read.csv("http://www.stat.berkeley.edu/users/nolan/data/sat.csv")

cor( satDF[ , c("expend","ratio","salary","frac", "sat")] )

coplot(sat ~ expend | frac, data = satDF, xlab = "Expenditure",
ylab = "SAT score")



lm.Ex = lm(sat ~ expend, data = satDF) 
lm.frac = lm(sat ~ frac, data = satDF)

summary(lm.Ex)

summary(lm.frac)


plot(residuals(lm.Ex) ~ satDF$frac, xlab = "Fraction of Eligible Students Taking SAT", ylab = "Residuals", main = "Model: SAT scores ~ Expenditures")


lm.ExFrac = lm(sat ~ expend + frac, data = satDF) 
lm.SalFrac = lm(sat ~ salary + frac, data = satDF) 
lm.RatFrac = lm(sat ~ ratio + frac, data = satDF)


summary(lm.ExFrac)

summary(lm.SalFrac)


summary(lm.RatFrac)


cor(residuals(lm(sat ~ frac, data = satDF)), residuals(lm(expend ~ frac, data = satDF)))



cor(residuals(lm(sat ~ frac, data = satDF)), residuals(lm(salary ~ frac, data = satDF)))



cor(residuals(lm(sat ~ frac, data = satDF)), residuals(lm(ratio ~ frac, data = satDF)))

lm.3 = lm(sat ~ salary + ratio + frac, data = satDF) summary(lm.3)



plot(rstandard(lm.3) ~ fitted(lm.3), xlab = "Fitted Values", ylab = "Standardized Residuals", main = "Model: sat ~ salary + ratio + frac")



coefficients(lm.3)["salary"] * sd(satDF$salary) / sd(satDF$sat)



coefficients(lm.3)["ratio"] * sd(satDF$ratio) / sd(satDF$sat)

plot(sat ~ frac, data = satDF) with(satDF, text(x = frac, y= sat, labels = State, cex = 0.5, pos = 4))




```



```{r, echo=FALSE}



```

